version: "3.9"

services:
  app:
    build: .
    container_name: pythox-x29-app
    ports:
      - "${HOST_PORT}:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
    restart: unless-stopped